<tr>
											<th>Club</th>
											<th>Points</th>
											<th>Matches</th>
											<th>Win</th>
											<th>draw</th>
											<th>lose</th>
											<th>GF</th>
											<th>GA</th>
											<th>GD</th>
										</tr>